#spring boot properties
spring:
  application.name: freePA
  datasource:
    url: jdbc:postgresql://localhost/freepa
    username: freepa
    password: freepa
    hikari.maximum-pool-size: 3
    
  #JPA
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true