#spring boot properties
spring:
  datasource:
    url: jdbc:postgresql://localhost/freepa-test
    username: freepa
    password: freepa
    hikari.maximum-pool-size: 3
    
  #JPA
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect